thoth-station/common

Pipfile.lock
Dependency rfc5424-logging-handler was used in version 1.1.0, but the current latest version is 1.1.2.
=> Automatic dependency update for rfc5424-logging-handler to version 1.1.2

Pipfile.lock
Dependency thoth-storages was used in version 0.0.26, but the current latest version is 0.0.28.
=> Automatic update of dependency thoth-storages from 0.0.26 to 0.0.28

thoth/common/logging.py
Port has to be explicitly casted to int and root logger obtained from the standard logging module.
=> Fix logging issues

thoth/common/openshift.py
Respect parameters that were supplied and fallback to infra namespace only if
namespace parameter was not supplied.
=> Fix gathering pod id from job name

thoth/common/helpers.py, thoth/common/openshift.py
I removed config.load_incluster_config() So that we can pass the files for debugging purpose.
```
o = OpenShift(openshift_api_url="https://ocp:443",
token_file="./token",
cert_file="./ca.crt")
o.get_pod_status(pod_id="podname", namespace="namespace")
```
Here is a test script https://gist.github.com/sub-mod/b101556dda3ab7cb22117a690e9a79ef
```
yum -y install libffi-devel
pip3 install requests pkiutils pyopenssl
```
create token and ca.crt file
```
oc whoami -t > /token
echo QUIT | openssl s_client -showcerts -connect <kubernetes-master-hostname>:8443 2>&1  | openssl x509 -text | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ca.crt
```
```
import os
from thoth.common import OpenShift
import urllib3
if __name__ == '__main__':
urllib3.disable_warnings()
environ = { …
```
=> Add InClusterConfigLoader to load SA and cert

thoth/common/openshift.py
As we want to have Amun as a separate application, infra namespace has to be
configurable for both applications separatelly.
=> Fix how amun and thoth infra namespace is handled

thoth/common/helpers.py
- prevents from using global default format string when formatting from different
datetime formats
modified:   helpers.py
=> Add format_datetime method to convert datetimes to default format

thoth/common/openshift.py
Fixes: https://github.com/thoth-station/metrics-exporter/issues/231
=> Fixed ResourceNotUniqueError in get_solver_names

thoth/common/openshift.py
There is a restriction in OpenShift metadata length of 63 digits. With 32 digits already being taken by workflow random digits and inspection random digits, there is not much space left for the inspection identifier.
The same reduction is proposed to be used in the inspection ID.
=> Use 8 random digits in the ID instead of 16

thoth/common/logging.py
Logs from the cluster:
Before:
```
2020-01-09 14:52:17,583 [1] INFO     thoth.adviser.pipeline_builder:202: Creating pipeline configuration
2020-01-09 14:52:17,604 [90] INFO     thoth.adviser.resolver:397: Resolving direct dependencies
2020-01-09 14:52:43,193 [90] INFO     thoth.adviser.resolver:673: Hold tight, Thoth is computing recommendations for your application...
```
After:
```
2020-01-09 14:52:17,583   1 INFO     thoth.adviser.pipeline_builder:202: Creating pipeline configuration
2020-01-09 14:52:17,604  90 INFO     thoth.adviser.resolver:397: Resolving direct dependencies
2020-01-09 14:52:43,193  90 INFO     thoth.adviser.resolver:673: Hold tight, Thoth is computing recommendations for your application...
```
=> I had to do it... it was so annoying

thoth/common/openshift.py
Fixed the spelling mistake causing the issue.
Fixes: https://github.com/thoth-station/build-analyzers/issues/134
Require a New Patch release.
=> Fixed the spelling mistake causing issue

thoth/common/openshift.py
Method to allow graph-sync-scheduler to schedule a graph-sync-job for build analyzer report sync. 
Related-To: https://github.com/thoth-station/build-analyzers/pull/140
=> function to sync build analyzers report

thoth/common/workflows.py
Remove `workflow-` prefix otherwise components will fail due to constraint in prefix name 
(e.g. `adviser-*` required in adviser id)
=> Remove prefix to avoid error in Thoth components

thoth/common/openshift.py
Issue encountered running graph-refresh-job with `THOTH_USE_ARGO` =1
```
---> Running application from Python script (app.py) ...
--
  | 2020-02-28 11:14:48,613   1 INFO     thoth.common:259: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'thoth-psi-stage' and integrations ['SqlalchemyIntegration']
  | 2020-02-28 11:14:48,620   1 INFO     thoth.common:297: Logging to rsyslog endpoint is turned off
  | 2020-02-28 11:14:48,890   1 INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2020-02-28 11:14:48,890   1 INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2020-02-28 11:14:48,939   1 WARNING  thoth.common.openshift:144: TLS verification when communicating with k8s/okd master is disabled
  | 2020-02-28 11:14:48,939   1 …
```
=> Migrate method to be used for graph-refresh-job switching to Argo for solvers

thoth/common/openshift.py, thoth/common/workflows.py
This commit fixes Workflow ID being reported by thamos instead of the adviser ID and it prevents thamos from failing to wait for an analysis if a Job has not yet been created.
=> Fixes for thamos advise

thoth/common/logging.py
From OpenShift logs:
```
/opt/app-root/lib/python3.6/site-packages/jsonformatter/jsonformatter.py:76: UserWarning: Current Python version is below 3.7.0, the key's order of dict may be different from the definition, Please Use `OrderedDict` replace.
--
  | "Current Python version is below 3.7.0, the key's order of dict may be different from the definition, Please Use `OrderedDict` replace.", UserWarning)
```
=> Remove warning produced by jsonformatter

thoth/common/openshift.py
- schedule_inspection warns about using argo workflows
=> Allow to set use_argo and initialize workflow_manager

thoth/common/logging.py
otherwise logs can be too verbose for many loggers
=> Set default loglevel to WARNING

thoth/common/openshift.py
Parallelism will be handled by Argo configuration based on cluster resources.
Allowed failures will not be taken into account with argo tasks.
=> Remove parallelism and allowed failures configuration

thoth/common/openshift.py
It's assigned to Argo template. This removes huge warning printed to logs.
=> Remove assignment of the Dockerfile

thoth/common/workflows.py
Example:
```
namespace: thoth-prod-tensorflow
label_selector: component=adviser
workflows: {'Failed': 177, 'Error': 53}
pods: {'trigger-finished-webhook': {'Succeeded': 177, 'Error': 1}, 'graph-sync-advise': {'Failed': 177, 'Error': 1}, 'advise': {'Succeeded': 177, 'Error': 52, 'Failed': 1}}
```
=> New methods to monitor Argo workflows

thoth/common/openshift.py
`output` is not mandatory if we use Argo workflows for solver
=> make output in solver optional

thoth/common/__init__.py, thoth/common/helpers.py
See https://github.com/thoth-station/python/pull/269
We move `Lazy` from python helpers to here to remove the issue of circular dependencies
=> move Lazy to common helpers from python helpers

thoth/common/openshift.py, thoth/common/workflows.py
Now that the SrcOpsMetrics project is part of thoth and has been renamed to `mi`, everything in common regarding to it should be also renamed. 
This PR fixes https://github.com/thoth-station/mi-scheduler/issues/30
=> Rename srcopsmetrics to mi

thoth/common/openshift.py
set source_type_enum None when soure_type not set
Fixes: #931 
=> set source_type_enum None when soure_type not set

thoth/common/openshift.py
```
2020-08-21 16:14:05,011  27 WARNING  thoth.common.openshift:298: Requested to assign parameter 'IMAGE_STREAM_NAMESPACE' (value 'thoth-infra-stage') to template but template does not provide the given parameter, forcing...
```
=> Remove IMAGE_STREAM_NAMESPACE env

thoth/common/workflows.py
provenance-checks fail as they are scheduled in middletier but the result obtaining logic expects them in backend namespace. They should run in backend namespace all the time.
Fixes: https://github.com/thoth-station/user-api/issues/1044
=> Provenance checks should be scheduled in backend namespace

thoth/common/helpers.py
.. so the links appear shorter in the terminal.
=> No need to provide html suffix

thoth/common/openshift.py
We need all workflows to be able to accept job_id because we are sending requests through kafka rather than directly through common.Openshift
=> allow job_id to be passed so we can return it

thoth/common/logging.py
=> Rely on S2I specific environment variable, no OpenShift build env vars

Pipfile, Pipfile.lock, requirements.txt, thoth/common/openshift.py
Update versions for compatibility between `argo-workflows`, `kubernetes` and `openshift` libraries
Argo > 2.10 maps to `Argo python client > 3.5` requires `Kubernetes ~11.0` and `openshift` needs to be updated accordingly.
- Update versions
- Adjust Openshift class
=> Update versions for compatibility between Argo, Kuberneter and Openshift

thoth/common/openshift.py
This PR is part of https://github.com/thoth-station/mi-scheduler/issues/26
All of the openshift related functionality from `mi-scheduler` was moved to `openshift` class.
=> Move openshift related code from mi-scheduler

thoth/common/openshift.py, thoth/common/workflows.py
https://github.com/thoth-station/mi-scheduler/pull/58
New submit and schedule methods for MI inspection of Kebechet 
the `submit_mi` and `schedule_mi_workflow` methods regarding general mi analysis remained untouched
=> Add submit and schedule kebechet methods

thoth/common/openshift.py
Fixes: #1058 
With this change, we will increase the number of bits needed to distinguish documents. 128. With this, we should be able to analyze 2.6×10^10 packages per solver with a probability of  10^(-18) for collision. Kubernetes pod name can hold up to 253 characters, this digest requires 32 characters, argo adds 11 characters to distinguish pods within workflow, cca ~20 is required for solver prefix and the rest is required for delimiters and we still have some free space.
https://en.wikipedia.org/wiki/Birthday_problem#Probability_table
=> Increase random bits used to distinguish workflows

thoth/common/openshift.py
With this change, we add datetime to the suffix generated. It will provide the capability to distinguish when the given document was generated just by looking at the document identifier. Another, more important aspect, is that the timestamp encoded will avoid any collisions considering additional suffix. It means that the hash generation in the exact same second would return the same 64 UUID hash, which probability is very close to zero given the random seed.
=> Revisit generating id to avoid hash collisions

thoth/common/openshift.py
Fixes: https://github.com/thoth-station/thoth-application/issues/848
When `job_id` is not supplied, THOTH_DOCUMENT_ID is an empty string.
=> Fix package-extract job id propagation

thoth/common/openshift.py, thoth/common/workflows.py
Related-to: 
https://github.com/thoth-station/thoth-application/pull/859
https://github.com/thoth-station/thoth-application/issues/629
run dependency monkey workload on the amun-inspection namespace
moving dependency moneky execution from middletier to amun-inspection to maximize on the resource consumption.
=> run dependency monkey workload on the amun-inspection namespace

thoth/common/openshift.py
Fixes: https://github.com/thoth-station/integration-tests/issues/128
User API schema validation fails as obtaining status of a node in argo workflow does not translate response to the required schema - rather it returns directly Kubernetes low lever pod info which is undesired.
=> Fix obtaining pod status for workflows

.pre-commit-config.yaml, thoth/common/openshift.py
thoth-station/kebechet#584
Add metadata to both kebechet-run-url which is triggered by `kebechet-admin` in workflow helpers as well as `adviser` so that the metadata can be passed when using advise and provenance checkers.  The metadata will be used by kebechet to construct PR and issue bodies. In the case of the advise and provenance manager, the metadata will be sent to adviser and provenance workflows and then be received by kebechet-run-results.
=> add metadata to relevant schedule methods

thoth/common/openshift.py
=> Provide an argument to run authenticated provenance-checks

thoth/common/workflows.py
We do not have argo workflows in graph namespace, let's utilize middletier namespace. Thanks to @harshad16 for spotting this issue.
=> Run purge workflows in middletier namespace

thoth/common/openshift.py
Passing package_update_info around is unnecessary. The information required is present in `kebechet_metadata`
=> get update info from kebechet meta

thoth/common/config/runtime_environment.py
```
2022-01-05 14:12:30,336 [1676235] WARNING  thoth.common.config.runtime_environment: Unknown configuration entry in the configuration file 'labels' with value None
```
=> Runtime environment entries can have labels associated

thoth/common/openshift.py
Related: https://github.com/thoth-station/s2i-thoth/issues/231#issuecomment-1029030336
=> Fix parsing solver name for Python 3.10

thoth/common/openshift.py
Fix the send_message assignment with default
Related-to: https://github.com/thoth-station/amun-api/issues/641
=> Fix the send_message assignment with default

mypy.ini, thoth/common/logging.py
Related to #1232 
- No
Remove parts of `logging.py` relative to `rfc5424logging` and syslog.
=> Drop rfc5424logging and syslog

thoth/common/openshift.py
Related to [more general mi workflow](https://github.com/thoth-station/thoth-application/pull/2432)
https://github.com/thoth-station/thoth-application/issues/1835
Adding new parameter `create_knowledge` for scheduling `mi` workflows.
`mi-scheduler` needs to be also changed
=> Add `create_knowledge` parameter, change workflow name

Pipfile, Pipfile.lock
Related to https://github.com/thoth-station/common/issues/1232
- No
=> Remove `rfc5424-logging-handler` from dependencies

thoth/common/openshift.py
We should not hardcode this behavior, rather have it configurable on the template level.
=> Send messages based on template defaults, do not hardcode

Pipfile, Pipfile.lock, requirements.txt
Fixes: https://github.com/thoth-station/common/issues/1251
Bumping version of PyYaml (which depends on Kubernetes, which depends on openshift) for CVE_2020_1747
=> bump kubernetes version for common image

thoth/common/openshift.py, thoth/common/workflows.py
Related to: https://github.com/thoth-station/thoth-application/issues/2513
Related to: https://github.com/thoth-station/management-api/issues/887 (common changes)
Creates a `schedule_sync_job` function and a function to submit a workflow for the sync job.
/cc @fridex 
/cc @harshad16
=> adding openshift function and schedule workflow for sync-job

thoth/common/openshift.py
Related to https://github.com/thoth-station/mi-scheduler/issues/249
In addition to underscores, uppercase letters are also not allowed for workflow names
=> Make workflows names lowercase [mi-scheduler]
