- thoth/common/__init__.py
- thoth/common/logging.py
> Generic wrappers to define verbose level on every method

- .coafile
- .zuul.yaml
- CHANGELOG.md
- Pipfile
- Pipfile.lock
- thoth/common/__init__.py
- thoth/common/logging.py
Starting with this release we have a Zuul-CI pipeline that:
* lints on Pull Requrest and gate/merge
* uploads to pypi (test) on tag
> preparing release 0.0.8: Zuul

- thoth/common/logging.py
Fixes: https://github.com/thoth-station/user-api/pull/125
> Change in var name

- thoth/common/logging.py
this fixes https://github.com/thoth-station/result-api/issues/39
> catching and logging a "[Errno -2] Name or service not known"

- setup.py
> Pin down Kubernetes and OpenShift clients to specific versions

- thoth/common/openshift.py
Relates: https://github.com/thoth-station/user-api/issues/222
> Fix built-in type shadowing

- thoth/common/logging.py
> fixed the typo

- thoth/common/openshift.py
> added get_jobs(), it will be used for thoth-metrics

- thoth/common/helpers.py
- thoth/common/openshift.py
Related to https://github.com/thoth-station/common/pull/174
> Refactor methods into pythonic way

- thoth/common/openshift.py
Related: https://github.com/thoth-station/user-api/pull/306
> Do not propagate force to actual package-extract run

- thoth/common/logging.py
Fixes: https://github.com/thoth-station/amun-api/issues/50
> Report error if sentry initialization fails

- .coafile
- .zuul.yaml
Depends-On: https://github.com/thoth-station/common/pull/190
> using thoht-* jobs now

- thoth/common/openshift.py
This way we can use workload-operator to perform job scheduling.
> Move Amun specific pieces to OpenShift class

- thoth/common/openshift.py
We need to explicitly set CPU and memory requests when getting OpenShift
template as we need requests expanded in the workload-operator.
> Assing memory and cpu requests when getting template

- thoth/common/openshift.py
Otherwise we can get into dead-lock where jobs are in image pull-backoff
waiting for builds to finish, but builds cannot be scheduled due to quota
reached.
> Treat builds as workload

- thoth/common/openshift.py
...they can be really annoying
> Disable urllib3 warnings

- thoth/common/exceptions.py
- thoth/common/openshift.py
Reverts thoth-station/common#291
> Revert "A temporary workaround for workload management"

- thoth/common/openshift.py
Related: https://github.com/thoth-station/adviser/pull/193
> Introduce limit latest versions parameter

- thoth/common/logging.py
- thoth/common/openshift.py
refactored retrieval of template to OpenShift._get_template(label_selector)
> refactored retrieval of template

- thoth/common/openshift.py
- configmap were being created in backend instead of middletier.
> minor fix for correct namespace

- thoth/common/openshift.py
Related: https://github.com/thoth-station/amun-api/issues/173
> Supply environment variable for registry and infra namespace for inspections

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/405
> Fix solver temlate handling

- thoth/common/openshift.py
New function to get all configmaps with a certaing label from a specific namespace.
> New function for all ConfigMaps

- thoth/common/openshift.py
Related: https://github.com/thoth-station/amun-api/issues/181
> Fix retrieving pod logs - use OpenShift API

- .coafile
Increase the limit for file line size
> Increase the limit for file line size

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/amun-api/issues/195
> Fix wrong argument handling

- .coafile
> Increase maximum lines per file

- thoth/common/openshift.py
- Support for build analysers scheduling
- Auto black changes 
> Support for build analysers scheduling

- thoth/common/openshift.py
Small change to environment variables to explicitly state Kebechet
> Changed env variable names

- thoth/common/openshift.py
Created a scheduler for package-analyzer
> schedule_package_analyzer

- thoth/common/openshift.py
Modified the names to standard convention
Related-to: https://github.com/thoth-station/build-analysers/pull/35
New Release Required
> Modified the names to standard convention

- thoth/common/openshift.py
New function to count jobs per status per label.
> New function to count status of specific jobs identifed by label, in a certain namespace

- thoth/common/openshift.py
Analysis id is not required for run_url
> Leftover parameter from copy paste

- requirements.txt
- setup.py
Until we implement extras logic to Thoth
> As we use Thoth to resolve dependencies, stop using extras

- thoth/common/openshift.py
Depends-On: https://github.com/thoth-station/package-analyzer/pull/34
> Add dry-run to package-analyzer

- thoth/common/openshift.py
Related: https://github.com/thoth-station/graph-refresh-job/pull/256
> Schedule solvers without transitive flag being set by default

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/484
> Improve error message shown when getting cluster resources

- thoth/common/logging.py
> Always log in UTC to be consistent with team members all over the world

- Pipfile
- Pipfile.lock
> relocked dependencies, cleaned up the coala deps

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/graph-sync-scheduler/issues/69
> Fix method name to comply with other methods

- .gitignore
- .zuul.yaml
- Pipfile
- Pipfile.lock
- mypy.ini
- setup.py
- thoth/common/__init__.py
- thoth/common/config/__init__.py
- thoth/common/config/base.py
- thoth/common/config/runtime_environment.py
- thoth/common/helpers.py
- thoth/common/json.py
- thoth/common/logging.py
- thoth/common/openshift.py
Convert this library to be compatible with type checking.
> Start using mypy for type checking

- Pipfile
- Pipfile.lock
- fixtures/workflows/hello-world.yaml
- mypy.ini
- requirements.txt
- tests/workflows.py
- thoth/common/__init__.py
- thoth/common/exceptions.py
- thoth/common/helpers.py
- thoth/common/openshift.py
- thoth/common/workflows.py
- thoth/common/workflows_test.py
> Workflow management

- Pipfile.lock
#550 should be closed and new patch release should be requested after this
> :pushpin: Relock

- thoth/common/workflows.py
modified:   thoth/common/workflows.py
> Make workflow management publicly consumable

- thoth/common/openshift.py
Related: https://github.com/thoth-station/storages/pull/1340 https://github.com/thoth-station/analyzer/pull/209
> Propagate document id into templates

- thoth/common/workflows.py
modified:   thoth/common/workflows.py
> Allow for different workflow and template namespaces

- thoth/common/workflows.py
modified:   thoth/common/workflows.py
> Fixed accessor to amun_infra_namespace attribute

- thoth/common/workflows.py
modified:   thoth/common/workflows.py
> Inspection Workflow template is stored in amun infra

- thoth/common/openshift.py
> Updated randbits to fix #568

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/566
> Correct bug in one function

- thoth/common/openshift.py
> Busy wait on configmap creation to make sure cm gets propagated in the cluster

- thoth/common/workflows.py
> WIP: Schedule adviser workflow

- thoth/common/openshift.py
- thoth/common/workflows.py
> Migration to Argo workflow for Adviser

- thoth/common/openshift.py
> Remove wrong default value to run Dependency Monkey and Adviser

- thoth/common/openshift.py
- thoth/common/workflows.py
> Solver runs with Argo workflows

- thoth/common/openshift.py
- thoth/common/workflows.py
> Correct solver id input

- thoth/common/openshift.py
Related-To: https://github.com/thoth-station/adviser/pull/769
> Rename template used by workload opeartor

- thoth/common/openshift.py
- thoth/common/workflows.py
> Thamos workflow for GitHub App Qeb-Hwt

- thoth/common/openshift.py
- thoth/common/workflows.py
> Modify method to accept None

- thoth/common/openshift.py
> Adjust exception for thamos advise workflow

- .gitignore
- setup.py
> added xml coverage report

- .coafile
- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
> added pre-commit and did a little bit of coala cleanup

- thoth/common/logging.py
Closes https://github.com/thoth-station/user-api/issues/740
Added missing commit.
> Added log error

- thoth/common/openshift.py
Depends-On: https://github.com/thoth-station/user-api/pull/758/files
> Extend parameters for Adviser

- thoth/common/openshift.py
> Add host parameter for Thamos GitHub App

- thoth/common/openshift.py
> Add method to retrieve image streams

- thoth/common/openshift.py
> Adjust parameters for Thamos Workflow

- thoth/common/openshift.py
> add missing parameter to advise method

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/667
Fixes: https://github.com/thoth-station/metrics-exporter/issues/289
Fixes: https://github.com/thoth-station/metrics-exporter/issues/287
New release of thoth-common is required.
> Change template name for Argo migration

- thoth/common/openshift.py
> Remove revision from metadata

- thoth/common/openshift.py
> Missing metadata parameters

- thoth/common/openshift.py
> Openshift methods for inspection workflows

- thoth/common/openshift.py
As discussed in https://github.com/thoth-station/amun-api/pull/265
> Added get_workflow_status method

- thoth/common/openshift.py
> Correct datatype

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/solver/issues/481
> Adjust inputs for solvers

- Pipfile
- Pipfile.lock
> Adjust Pipfile and Pipfile.lock

- .thoth.yaml
> Adjust .thoth.yaml

- thoth/common/openshift.py
> Generalize variables for Ceph storage for workflow

- thoth/common/openshift.py
Tested and CM already updated.
> Modify logic of get_solver_names not to depend on Openshift template

- thoth/common/openshift.py
> Add re_run_adviser_id metadata for qeb-hwt app

- requirements.txt
> added the missing jsonformatter

- thoth/common/openshift.py
> Adjust id for qeb-hwt workflow

- thoth/common/logging.py
Related: https://github.com/thoth-station/user-api/pull/828 https://github.com/thoth-station/management-api/pull/422
> Force JSON logger for all registered loggers

- thoth/common/openshift.py
Related: https://github.com/thoth-station/adviser/pull/888
> Propagate THOTH_ADVISER_DEV parameter to adviser runs

- thoth/common/openshift.py
provide image stream name while processing template
Adviser:
https://github.com/thoth-station/adviser/blob/84bcd3d75c6e853965fe8e8647bd516a15bf46fa/openshift/adviser-template.yaml#L99
https://github.com/thoth-station/adviser/blob/84bcd3d75c6e853965fe8e8647bd516a15bf46fa/openshift/job-adviser-template.yaml#L29
https://github.com/thoth-station/adviser/blob/84bcd3d75c6e853965fe8e8647bd516a15bf46fa/openshift/job-provenanceChecker-template.yaml#L27
https://github.com/thoth-station/adviser/blob/84bcd3d75c6e853965fe8e8647bd516a15bf46fa/openshift/job-dependencyMonkey-template.yaml#L30
Solver:
https://github.com/thoth-station/solver/blob/ce46035522b848eea1aeca856f534503d163f7d1/openshift/solve_and_sync-template.yaml#L57
Amun-api: …
> provide imagestream name while processing template

- thoth/common/openshift.py
- thoth/common/workflows.py
Added methods to pass initiate kebechet argo workflow from webhook.
> Added workflow functions

- thoth/common/workflows.py
Please create a new release, for this PR
> Renamed to kebechet

- thoth/common/openshift.py
Moved json serialization to thoth-common.
> Moved json serialization

- thoth/common/__init__.py
- thoth/common/enums.py
- thoth/common/openshift.py
> Add source type for Thoth adviser integrations

- thoth/common/exceptions.py
> Add exception for integrations

- thoth/common/enums.py
- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/812
- Adjust enums
- Remove is_s2i flag
> Adjust enums

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/810
> Use solvers ConfigMap

- thoth/common/exceptions.py
- thoth/common/openshift.py
> New check method for Qeb-HWt inputs

- thoth/common/openshift.py
> Add missing parameters

- thoth/common/exceptions.py
- thoth/common/openshift.py
> Introduce logic for solver

- thoth/common/openshift.py
> Missing self

- thoth/common/openshift.py
> Missing self in methods

- .pre-commit-config.yaml
Related: https://github.com/thoth-station/common/pull/833
> only change pre-commit config

- .pre-commit-config.yaml
- thoth/common/openshift.py
> Be consistent

- .pre-commit-config.yaml
- thoth/common/openshift.py
> :sparkles: standard pre-commit-config

- thoth/common/exceptions.py
- thoth/common/openshift.py
> Introudce method for verifying Kebechet inputs

- thoth/common/openshift.py
> Correct serialization of Enum

- thoth/common/helpers.py
Fixes: https://github.com/thoth-station/python/issues/276
> Accept alternative datetime format string used by PyPI

- thoth/common/helpers.py
- thoth/common/openshift.py
- thoth/common/workflows.py
```
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 315, "funcname": "set_template_parameters", "created": 1592926714.4684837, "asctime": "2020-06-23 15:38:34,468", "msecs": 468.48368644714355, "relative_created": 1007318.6655044556, "process": 1, "message": "Requested to assign parameter 'IMAGE_STREAM_NAMESPACE' (value 'thoth-test-core') to template but template does not provide the given parameter, forcing..."}
```
> Remove variable not required

- thoth/common/openshift.py
Related- https://github.com/thoth-station/user-api/issues/908
Handling after receiving upper case enum string.
> Source type enum fix

- thoth/common/openshift.py
- thoth/common/workflows.py
Closes: https://github.com/thoth-station/common/issues/875
> Build analysis workflow

- thoth/common/openshift.py
- thoth/common/workflows.py
Fixes: https://github.com/thoth-station/common/issues/873
> Use Argo workflows for package-extract

- thoth/common/openshift.py
- thoth/common/workflows.py
Remove Methods to schedule single SI.
Introduce method to schedule a complete SI workflow using all SI analyzers.
> Add methods to schedule SI workflow

- thoth/common/openshift.py
- thoth/common/workflows.py
> Use singular

- thoth/common/openshift.py
- thoth/common/workflows.py
Let's create whole revsolver workflow, it will be easier to handle.
> Introduce reverse solver workflow

- thoth/common/openshift.py
> Make methods static

- thoth/common/openshift.py
Added a wrapper around `get_workflow_status`. 
Related to https://github.com/thoth-station/user-api/issues/965
> Added workflow status wrapper

- thoth/common/openshift.py
Related: https://github.com/thoth-station/amun-api/issues/486 https://github.com/thoth-station/amun-api/issues/487
> Introduce raw specification parameter to be used when storing on Ceph

- thoth/common/openshift.py
Related: https://github.com/thoth-station/user-api/issues/1018
> Add a routine for obtaining logs from workflow nodes

- thoth/common/openshift.py
Related: https://github.com/thoth-station/adviser/pull/1159 https://github.com/thoth-station/management-api/pull/551
> Introduce a way to parametrize adviser's predictor

- thoth/common/openshift.py
Related: https://github.com/thoth-station/thoth-application/pull/347
> Allow users to pick predictor to be used

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/359
> Add more information related to invalid response size

- thoth/common/config/runtime_environment.py
> Do not propagate private attribute in to_doct() method

- thoth/common/__init__.py
- thoth/common/helpers.py
- thoth/common/openshift.py
```python
>>> from thoth.common import get_justification_link as jl
>>> jl("oom")
'https://thoth-station.ninja/justifications/oom.html'
```
> Provide a method for obtaining a link to justification description

- thoth/common/helpers.py
> Make links to justifications shorter so they fit to terminal output

- thoth/common/openshift.py
- thoth/common/workflows.py
https://github.com/thoth-station/messaging/pull/235
> thamos->qebhwt for workflow name

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/issues/986
> Fix predictor config propagation when scheduling adviser

- thoth/common/workflows.py
https://github.com/thoth-station/investigator/issues/155
> add optional limit for workflows

- thoth/common/openshift.py
> Improve message logged when obtaining wf node log from cluster fails

- thoth/common/openshift.py
Fixes: https://github.com/thoth-station/common/pull/994#issuecomment-696039066
- Fixing the pre-commit errors.
fix pre-commit for common
> fix pre-commit for common

- tests/workflows_test.py
- thoth/common/openshift.py
We need deployment name for send messages
> Qebhwt needs deployment name

- thoth/common/openshift.py
- thoth/common/workflows.py
Depends on - https://github.com/thoth-station/thoth-application/pull/564
Related - https://github.com/thoth-station/common/issues/1009
> Added method to initiate kebechet run-url workflow

- thoth/common/workflows.py
https://github.com/thoth-station/common/issues/1014
argo api changed slightly
> check if workflow has started

- thoth/common/openshift.py
- thoth/common/workflows.py
Added calling method for Kebechet Administrator 
Related - https://github.com/thoth-station/workflow-helpers/issues/148
> Added method to call kebechet admin workflow

- thoth/common/logging.py
> Turn missing env variable warning into an error

- thoth/common/logging.py
- thoth/common/openshift.py
Related-To: https://github.com/thoth-station/user-api/issues/1092
> get workflow node status

- thoth/common/openshift.py
- thoth/common/workflows.py
Depends on: https://github.com/thoth-station/thoth-application/pull/480
Related: https://github.com/thoth-station/thoth-application/issues/398
Function calls for new graph-sync workflow
> schedule graph sync workflow

- Pipfile
- Pipfile.lock
- requirements.txt
Fixes: https://github.com/thoth-station/s2i-thoth/issues/100#issue-753398656
> Pin argo-workflows to a version before 4

- .github/ISSUE_TEMPLATE/deliver_missing_module.md
included issue template to release missing module
> included issue template to release missing module

- thoth/common/__init__.py
- thoth/common/helpers.py
- thoth/common/openshift.py
Related: https://github.com/thoth-station/thamos/issues/652
> Move normalization functions to helpers

- Pipfile
- Pipfile.lock
- thoth/common/workflows.py
Fixes: https://github.com/thoth-station/common/issues/1059
> Remove AttrDict from requirements

- thoth/common/openshift.py
Related: https://github.com/thoth-station/investigator/pull/393
Related: https://github.com/thoth-station/user-api/pull/1171
Related: https://github.com/thoth-station/messaging/pull/326
… Explain your changes.
> Propagate build log document id to build analysis workflow

- thoth/common/openshift.py
Related: https://github.com/thoth-station/messaging/pull/330
> Extend parameters supplied to build analysis

- thoth/common/openshift.py
Related-To: https://github.com/thoth-station/storages/issues/2080
> Add method to schedule graph-update-schema job

- thoth/common/openshift.py
Related: https://github.com/thoth-station/thoth-application/pull/735/
> Provide image metadata for package-extract

- thoth/common/openshift.py
> Provide additional build-analysis metadata so documents are traceable

- thoth/common/openshift.py
Related: https://github.com/thoth-station/storages/issues/2169
> Add is_external flag to build analysis

- thoth/common/config/hardware_information.py
- thoth/common/config/runtime_environment.py
Related: https://github.com/thoth-station/user-api/pull/1212
Related: https://github.com/thoth-station/thamos/pull/672
> Extend Thamos configuration file

- .pre-commit-config.yaml
- thoth/common/enums.py
thoth-station/kebechet#584
Create an enum representing the different internal triggers
> add enum for internal triggers

- thoth/common/openshift.py
https://github.com/thoth-station/thoth-application/pull/786/files
add params for sending message and whether graph-sync should force sync
> Thoth application#398

- thoth/common/openshift.py
Related: https://github.com/thoth-station/adviser/pull/1670/
> Do not propagate request data via messaging

- thoth/common/openshift.py
Related: https://github.com/thoth-station/thoth-application/issues/946
> Add flag to optionally sync results of package-extract

- thoth/common/config/runtime_environment.py
Not all fields are correctly parsed. This patch addresses the issue.
> Fix parsing runtime environment entries

- Pipfile
- Pipfile.lock
- requirements.txt
> Pin openshift to help Pipenv resolve the stack

- tests/workflows_test.py
- thoth/common/openshift.py
https://github.com/thoth-station/mi-scheduler/issues/76#issuecomment-784871942
> Add knowledge_path as parameter for schedule_mi_workflow

- thoth/common/openshift.py
https://github.com/thoth-station/thoth-application/pull/987
One thing to note is that as of now we assume our web-hooks are coming from GitHub
> pass slug to kebechet workflow

- thoth/common/openshift.py
https://github.com/thoth-station/adviser/pull/1625/files
> thoth-adviser metadata

- thoth/common/openshift.py
Related to https://github.com/thoth-station/thoth-application/pull/1098#event-4497551515
> Add additional configuration as parameter

- thoth/common/openshift.py
Related: https://github.com/thoth-station/common/pull/1141
> Be consistent with env vars supplied

- thoth/common/openshift.py
Related: https://github.com/thoth-station/thoth-application/pull/1132/files
> Provide an argument to run authenticated advises

- README.rst
> Minor improvements to docs

- thoth/common/openshift.py
Related: https://github.com/thoth-station/thoth-application/pull/1237
Related: https://github.com/thoth-station/thoth-application/pull/1236
> Make graph namespace available to the OpenShift adapter

- thoth/common/openshift.py
- thoth/common/workflows.py
Related: https://github.com/thoth-station/thoth-application/issues/808
> Introduce methods for scheduling purge workflows

- mypy.ini
- thoth/common/openshift.py
Related: https://github.com/thoth-station/storages/issues/2308
> Provide force_sync to solver schedule methods

- .prow.yaml
- mypy.ini
- setup.py
> updating the pytest fixes

- thoth/common/enums.py
- thoth/common/exceptions.py
- thoth/common/logging.py
- thoth/common/openshift.py
- thoth/common/workflows.py
Related-to: https://github.com/thoth-station/user-api/issues/1454
> Remove qeb-hwt and github-app bits

- thoth/common/exceptions.py
- thoth/common/openshift.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/615
Add method to expose configured cache configuration.
> Introduce method to expose cache expiration

- thoth/common/openshift.py
Related to https://github.com/thoth-station/mi-scheduler/pull/190
Add new merge path variable to the scheduling of mi workflows
> Add merge path to schedule mi workflows

- setup.py
- thoth/common/openshift.py
- thoth/common/workflows.py
https://github.com/thoth-station/thoth-application/pull/1965
For scheduling new workflow
> add method to schedule thoth-repo-init workflow

- thoth/common/config/hardware_information.py
> Fix typing for CPU and GPU properties

- .pre-commit-config.yaml
- thoth/common/openshift.py
https://github.com/thoth-station/workflow-helpers/issues/371
> if slug is None then param should not be passed

- .pre-commit-config.yaml
- .prow.yaml
- Pipfile
- Pipfile.lock
- mypy.ini
- thoth/common/openshift.py
#1250 
Testing done
we have removed the mypy check for now, will be included in a separate PR.
> fix pre-commit by removing mypy 

- thoth/common/openshift.py
Fixes https://github.com/thoth-station/thoth-application/issues/2503
SSIA
> Replace slash with dash in repo slug [scheduling mi workflows]

- OWNERS
> 🥹 moving @fridex in the OWNERS file, thanks for all the great work!!!

- .pre-commit-config.yaml
- .thoth.yaml
- OWNERS
HouseKeeping: Updated OWNERS and pre-commit changes
> :recycle: HouseKeeping: Updated OWNERS and pre-commit changes

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- mypy.ini
- thoth/common/config/base.py
- thoth/common/config/runtime_environment.py
- thoth/common/logging.py
- thoth/common/workflows.py
Closes https://github.com/thoth-station/common/issues/1252
SSIA
> Add mypy back to pre-commit

- Pipfile
- Pipfile.lock
Pinned Kubernetes version to 11.0.0
Fixes: https://github.com/thoth-station/common/issues/1273
> Pinned Kubernetes version to 11.0.0

- requirements.txt
> Fix pytest

- thoth/common/openshift.py
Related to https://github.com/thoth-station/mi-scheduler/issues/249
SSIA
> Remove underscores from repository name [mi-scheduler workflow naming]

- OWNERS
Related to #1295 
`mi` and `mi-scheduler` related code is present both in `workflows.py` and also `openshift.py` files, therefore I suggest adding myself as a maintainer, so I can be able to make release requests, too
> Add @xtuchyna as maintainer
